# Generated by Django 4.1.3 on 2022-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyearapp', '0002_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='person',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
